// <auto-generated />
using System;
using System.Collections.Generic;
using Bintainer.Modules.Inventory.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bintainer.Modules.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260307212930_RenamePartsToComponentsAndAddNewTables")]
    partial class RenamePartsToComponentsAndAddNewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Bins.Bin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<Guid>("StorageUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_unit_id");

                    b.HasKey("Id")
                        .HasName("pk_bins");

                    b.HasIndex("StorageUnitId")
                        .HasDatabaseName("ix_bins_storage_unit_id");

                    b.ToTable("bins", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.BomImports.BomImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("matched_count");

                    b.Property<int>("NewCount")
                        .HasColumnType("integer")
                        .HasColumnName("new_count");

                    b.Property<int>("TotalLines")
                        .HasColumnType("integer")
                        .HasColumnName("total_lines");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bom_imports");

                    b.ToTable("bom_imports", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.ToTable("categories", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Compartments.Compartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BinId")
                        .HasColumnType("uuid")
                        .HasColumnName("bin_id");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_compartments");

                    b.HasIndex("BinId")
                        .HasDatabaseName("ix_compartments_bin_id");

                    b.HasIndex("ComponentId")
                        .HasDatabaseName("ix_compartments_component_id");

                    b.ToTable("compartments", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Components.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<string, string>>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DetailedDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detailed_description");

                    b.Property<Guid?>("FootprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("footprint_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("LowStockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("low_stock_threshold");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("ManufacturerPartNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer_part_number");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_number");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPartNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_part_number");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tags");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_components");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_components_category_id");

                    b.HasIndex("FootprintId")
                        .HasDatabaseName("ix_components_footprint_id");

                    b.ToTable("components", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Footprints.Footprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_footprints");

                    b.ToTable("footprints", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.ToTable("inventories", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Movements.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid?>("CompartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("compartment_id");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SourceCompartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_compartment_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_movements");

                    b.HasIndex("CompartmentId")
                        .HasDatabaseName("ix_movements_compartment_id");

                    b.HasIndex("ComponentId")
                        .HasDatabaseName("ix_movements_component_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_movements_date");

                    b.ToTable("movements", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.StorageUnits.StorageUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Columns")
                        .HasColumnType("integer")
                        .HasColumnName("columns");

                    b.Property<int>("CompartmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("compartment_count");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.HasKey("Id")
                        .HasName("pk_storage_units");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_storage_units_inventory_id");

                    b.ToTable("storage_units", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Bins.Bin", b =>
                {
                    b.HasOne("Bintainer.Modules.Inventory.Domain.StorageUnits.StorageUnit", null)
                        .WithMany("Bins")
                        .HasForeignKey("StorageUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bins_storage_units_storage_unit_id");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Categories.Category", b =>
                {
                    b.HasOne("Bintainer.Modules.Inventory.Domain.Categories.Category", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Compartments.Compartment", b =>
                {
                    b.HasOne("Bintainer.Modules.Inventory.Domain.Bins.Bin", null)
                        .WithMany("Compartments")
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compartments_bins_bin_id");

                    b.HasOne("Bintainer.Modules.Inventory.Domain.Components.Component", null)
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_compartments_components_component_id");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Components.Component", b =>
                {
                    b.HasOne("Bintainer.Modules.Inventory.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_components_categories_category_id");

                    b.HasOne("Bintainer.Modules.Inventory.Domain.Footprints.Footprint", null)
                        .WithMany()
                        .HasForeignKey("FootprintId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_components_footprints_footprint_id");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Movements.Movement", b =>
                {
                    b.HasOne("Bintainer.Modules.Inventory.Domain.Compartments.Compartment", null)
                        .WithMany()
                        .HasForeignKey("CompartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_movements_compartments_compartment_id");

                    b.HasOne("Bintainer.Modules.Inventory.Domain.Components.Component", null)
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movements_components_component_id");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.StorageUnits.StorageUnit", b =>
                {
                    b.HasOne("Bintainer.Modules.Inventory.Domain.Inventories.Inventory", null)
                        .WithMany("StorageUnits")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storage_units_inventories_inventory_id");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Bins.Bin", b =>
                {
                    b.Navigation("Compartments");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Categories.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Inventories.Inventory", b =>
                {
                    b.Navigation("StorageUnits");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.StorageUnits.StorageUnit", b =>
                {
                    b.Navigation("Bins");
                });
#pragma warning restore 612, 618
        }
    }
}
