// <auto-generated />
using System;
using Bintainer.Modules.Inventory.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bintainer.Modules.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260308053230_AddIsActiveToBinsAndCompartments")]
    partial class AddIsActiveToBinsAndCompartments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Bins.Bin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<Guid>("StorageUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_unit_id");

                    b.HasKey("Id")
                        .HasName("pk_bins");

                    b.HasIndex("StorageUnitId")
                        .HasDatabaseName("ix_bins_storage_unit_id");

                    b.ToTable("bins", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Compartments.Compartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BinId")
                        .HasColumnType("uuid")
                        .HasColumnName("bin_id");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_compartments");

                    b.HasIndex("BinId")
                        .HasDatabaseName("ix_compartments_bin_id");

                    b.ToTable("compartments", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.ToTable("inventories", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Movements.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid?>("CompartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("compartment_id");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SourceCompartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_compartment_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_movements");

                    b.HasIndex("CompartmentId")
                        .HasDatabaseName("ix_movements_compartment_id");

                    b.HasIndex("ComponentId")
                        .HasDatabaseName("ix_movements_component_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_movements_date");

                    b.ToTable("movements", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.StorageUnits.StorageUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Columns")
                        .HasColumnType("integer")
                        .HasColumnName("columns");

                    b.Property<int>("CompartmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("compartment_count");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.HasKey("Id")
                        .HasName("pk_storage_units");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_storage_units_inventory_id");

                    b.ToTable("storage_units", "inventory");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Bins.Bin", b =>
                {
                    b.HasOne("Bintainer.Modules.Inventory.Domain.StorageUnits.StorageUnit", null)
                        .WithMany("Bins")
                        .HasForeignKey("StorageUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bins_storage_units_storage_unit_id");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Compartments.Compartment", b =>
                {
                    b.HasOne("Bintainer.Modules.Inventory.Domain.Bins.Bin", null)
                        .WithMany("Compartments")
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compartments_bins_bin_id");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Movements.Movement", b =>
                {
                    b.HasOne("Bintainer.Modules.Inventory.Domain.Compartments.Compartment", null)
                        .WithMany()
                        .HasForeignKey("CompartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_movements_compartments_compartment_id");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.StorageUnits.StorageUnit", b =>
                {
                    b.HasOne("Bintainer.Modules.Inventory.Domain.Inventories.Inventory", null)
                        .WithMany("StorageUnits")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storage_units_inventories_inventory_id");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Bins.Bin", b =>
                {
                    b.Navigation("Compartments");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.Inventories.Inventory", b =>
                {
                    b.Navigation("StorageUnits");
                });

            modelBuilder.Entity("Bintainer.Modules.Inventory.Domain.StorageUnits.StorageUnit", b =>
                {
                    b.Navigation("Bins");
                });
#pragma warning restore 612, 618
        }
    }
}
